### PR TITLE
Remove async driver support from the KG creation pipeline

### PR DESCRIPTION
**Pull request by alexthomas93**
# Description

This PR removes support for the neo4j.AsyncDriver in the KG creation pipeline. It eliminates an associated utility function and updates the Neo4jWriter component. Additionally, it updates the relevant examples and unit tests to align with these changes.

## Type of Change
- [ ] New feature
- [X] Bug fix
- [X] Breaking change
- [ ] Documentation update
- [ ] Project configuration change

## Complexity

Complexity: Medium

## How Has This Been Tested?
- [X] Unit tests
- [X] E2E tests
- [X] Manual tests

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [X] Documentation has been updated
- [X] Unit tests have been updated
- [ ] E2E tests have been updated
- [X] Examples have been updated
- [ ] New files have copyright header
- [X] CLA (https://neo4j.com/developer/cla/) has been signed
- [ ] CHANGELOG.md updated if appropriate

### CODE REVIEW

**Comment by alexthomas93** [comment]
@CodiumAI-Agent /update_changelog

**Review by stellasia — COMMENTED** [review]
LGTM, much simpler! Before merging, can you check the doc please? I think we added a note here about which parameters to tune to improve performances, maybe `max_concurrency` is mentionned.

**Comment by alexthomas93** [comment]
> LGTM, much simpler! Before merging, can you check the doc please? I think we added a note there about which parameters to tune to improve performances, maybe `max_concurrency` is mentionned.

Done!

**Review by stellasia — APPROVED** [review]
🧯

**Pull request merged**
